# Generated by Django 4.2.23 on 2025-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('mission_type', models.CharField(max_length=100)),
                ('people_count', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('leave_type', models.CharField(choices=[('maladie', 'Congé Maladie'), ('annuel', 'Congé Annuel'), ('maternite', 'Congé Maternité')], max_length=20)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address_during_leave', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('nationality', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('birth_place', models.CharField(default='', max_length=150)),
                ('full_address', models.TextField(default='')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('emergency_contact_name', models.CharField(default='', max_length=150)),
                ('emergency_contact_phone', models.CharField(default='', max_length=20)),
                ('job_type', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Interim', 'Interim')], default='', max_length=10)),
                ('diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('additional_training', models.TextField(blank=True, null=True)),
                ('professional_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('language_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('B1', 'B1'), ('B2', 'B2')], max_length=2, null=True)),
                ('current_position', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('moral_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('employment_type_field', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Interim', 'Interim')], default='', max_length=10)),
                ('hire_date', models.DateField(null=True)),
                ('rattached_service', models.CharField(max_length=150, null=True)),
                ('occupied_role', models.CharField(max_length=150, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probation_period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Interim', 'Interim')], max_length=10)),
                ('job_title', models.CharField(max_length=255)),
                ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requesting_service', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status_field', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critique', 'Critique')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
