# Generated by Django 4.2.23 on 2025-09-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
    ]
