# Generated by Django 4.2.23 on 2025-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_appuserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.DateField()),
                ('email', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_requests',
            },
        ),
    ]
