# Generated by Django 4.2.23 on 2025-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_conge_alter_employee_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('mission_type', models.CharField(max_length=100)),
                ('people_count', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
