# Generated by Django 4.2.23 on 2025-09-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='prenom',
            field=models.TextField(),
        ),
    ]
