# Generated by Django 4.2.23 on 2025-09-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_testmodel_email_alter_testmodel_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('nationality', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('birth_place', models.CharField(default='', max_length=150)),
                ('full_address', models.TextField(default='')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('emergency_contact_name', models.CharField(default='', max_length=150)),
                ('emergency_contact_phone', models.CharField(default='', max_length=20)),
                ('job_type', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Interim', 'Interim')], default='', max_length=10)),
                ('diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('additional_training', models.TextField(blank=True, null=True)),
                ('professional_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('language_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('B1', 'B1'), ('B2', 'B2')], max_length=2, null=True)),
                ('current_position', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('moral_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('employment_type_field', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Interim', 'Interim')], default='', max_length=10)),
                ('hire_date', models.DateField(null=True)),
                ('rattached_service', models.CharField(max_length=150, null=True)),
                ('occupied_role', models.CharField(max_length=150, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probation_period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ita-employees-list',
            },
        ),
    ]
