# Generated by Django 4.2.23 on 2025-09-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_assignmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Interim', 'Interim')], max_length=10)),
                ('job_title', models.CharField(max_length=255)),
                ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requesting_service', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status_field', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critique', 'Critique')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
