# Generated by Django 4.2.23 on 2025-09-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_itaemployeemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itaemployeemodel',
            table='ita_employees_list',
        ),
    ]
