# Generated by Django 4.2.23 on 2025-09-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_appuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table='ita_staff_users',
        ),
    ]
