# Generated by Django 4.2.23 on 2025-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_appuser_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created_at',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='appuser',
            name='updated_at',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
